# Generated by Django 5.0.6 on 2024-05-20 11:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scrapping_process", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_name", models.CharField(max_length=128)),
                ("base_link", models.CharField(max_length=512)),
                (
                    "scrapping_process",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_configs",
                        to="scrapping_process.scrappingprocess",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="providers",
                        to="providers.providerconfig",
                    ),
                ),
            ],
        ),
    ]
