# Generated by Django 5.0.6 on 2024-05-20 11:28

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
        ("scrapping_process", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="config",
        ),
        migrations.AddField(
            model_name="provider",
            name="base_link",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="provider",
            name="scrapping_process",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provider_configs",
                to="scrapping_process.scrappingprocess",
            ),
        ),
        migrations.DeleteModel(
            name="ProviderConfig",
        ),
    ]
