# Generated by Django 5.0.6 on 2024-05-21 07:58

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0002_remove_provider_config_provider_base_link_and_more"),
        ("scrapping_process", "0005_remove_scrappingstep_seniorities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="scrapping_process",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="providers",
                to="scrapping_process.scrappingprocess",
            ),
        ),
    ]
