x-env-vars: &env-vars
  env_file:
    - .env.dev

services:
  app-base:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.base
      tags:
        - app-base
    <<: *env-vars

  app-base-celery:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.base.celery
      tags:
        - app-base-celery
    depends_on:
      - app-base
    <<: *env-vars

  rabbitmq:
    image: "rabbitmq:3.13"
    ports:
      # https://www.rabbitmq.com/docs/networking#ports
      - "5671:5671"
      - "5672:5672"
      - "4368:4369"

  app-celery-worker:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.celery
    depends_on:
      - app-base-celery
      - rabbitmq
    restart: on-failure
    <<: *env-vars

  app-celery-beat:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.celery.beat
    depends_on:
      - app-base-celery
      - rabbitmq
    restart: on-failure
    <<: *env-vars

  app-db:
    image: "postgres:16-bookworm"
    restart: always
    ports:
      - "5432:5432"
    <<: *env-vars

  app-backend:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.backend
    depends_on:
      - app-base
      - app-db
      - app-celery-worker
      - app-celery-beat
    ports:
      - "8000:8000"
    <<: *env-vars
