# Generated by Django 5.0.6 on 2024-05-20 12:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapping_process", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scrappingstep",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="scrappingstep",
            name="key_words",
        ),
        migrations.AlterField(
            model_name="scrappingstep",
            name="seniorities",
            field=models.ManyToManyField(
                null=True,
                related_name="scrapping_steps",
                to="scrapping_process.seniority",
            ),
        ),
        migrations.AddField(
            model_name="scrappingstep",
            name="key_words",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
