# Generated by Django 5.0.6 on 2024-05-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "scrapping_process",
            "0003_scrappingstep_many_alter_scrappingstep_seniorities",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="scrappingstep",
            old_name="many",
            new_name="get_many_elements",
        ),
    ]
