# Generated by Django 5.0.6 on 2024-05-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapping_process", "0004_rename_many_scrappingstep_get_many_elements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrappingstep",
            name="seniorities",
        ),
    ]
