# Generated by Django 5.0.6 on 2024-05-21 09:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapping_process", "0005_remove_scrappingstep_seniorities"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrappingstep",
            name="is_next_page_step",
            field=models.BooleanField(default=False),
        ),
    ]
