# Generated by Django 5.0.6 on 2024-05-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapping_process", "0006_scrappingstep_is_next_page_step"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Seniority",
        ),
    ]
