# Generated by Django 5.0.6 on 2024-05-23 11:10

from django.db import migrations

from scrapping_process.data_migrations.load_initial_data import LoadInitialDataMigration


class Migration(migrations.Migration):

    dependencies = [
        ("scrapping_process", "0007_delete_seniority"),
    ]

    operations = [
        migrations.RunPython(LoadInitialDataMigration.apply),
    ]
