FROM app-base as app-base-celery

# installs Firefox and Geckodriver to be used for scrapping
RUN apt install firefox-esr --yes && apt install wget --yes
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz -O ~/geckodriver.tar.gz
RUN tar -xzf ~/geckodriver.tar.gz -C ~/
RUN chmod +x ~/geckodriver
