# Generated by Django 5.0.6 on 2024-05-20 11:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=512)),
                (
                    "seniority",
                    models.CharField(
                        choices=[
                            ("junior", "junior"),
                            ("mid", "mid"),
                            ("regular", "regular"),
                            ("senior", "senior"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_offers",
                        to="providers.provider",
                    ),
                ),
            ],
        ),
    ]
