# Generated by Django 5.0.6 on 2024-05-20 14:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="link",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
