# Generated by Django 5.0.6 on 2024-05-21 06:19

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_alter_joboffer_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="joboffer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
