# Generated by Django 5.0.6 on 2024-05-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0003_joboffer_created_at_joboffer_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joboffer",
            name="seniority",
        ),
    ]
