# Generated by Django 5.0.6 on 2024-05-27 11:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0004_remove_joboffer_seniority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="link",
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
